#!/bin/bash 

theme="$HOME/.themes/colors/${1}.ini"
echo "applying $theme..."

#list of configs to update
configdir="$HOME/.config/"
dots[1]="tofi/config"
dots[2]="kitty/colors.conf"
dots[3]="eww/themes/template.scss"
dots[4]="../dotfiles2/firefox/chrome/colors.css"
dots[5]="hypr/theme.conf"
dots[6]="dunst/dunstrc"
dots[7]="BetterDiscord/themes/template.theme.css"
#spicetify
#QT
#GTK

#update configs
for dot in ${dots[@]}; do
    path="$configdir$dot"
    template="$path.j2"
    
    j2 $template $theme -o $path &
    echo "...applied to $path"
done

#vscode
echo "VScode..."
syntax="$HOME/.themes/syntax.ini"
code="$HOME/.config/Code/User/settings.json"
j2 $syntax.j2 $theme -o $syntax
j2 $code.j2 $syntax -o $code &


#update running apps
sleep 0.2
echo "reloading configs..." 
eww -c "$configdir/eww/bar" reload
eww -c "$configdir/eww/dashboard" reload &
hyprctl reload 
pkill dunst 
pkill -SIGUSR1 kitty

#change wallpaper
echo "changing wallpaper..."
img=$(sed -nr '/^\[img\]/ { :l /^wallpaper[ ]*=/ { s/[^=]*=[ ]*//; p; q;}; n; b l;}' $theme)
echo $HOME$img
swww img $HOME$img --transition-step 30

echo "done!"
