#!/bin/bash 

theme="$HOME/.themes/${1}.ini"
echo "applying $theme..."

#list of configs to update
configdir="$HOME/.config/"
dots[1]="tofi/config"
dots[2]="kitty/colors.conf"
dots[3]="eww/themes/template.scss"
dots[4]="../dotfiles2/firefox/chrome/colors.css"
dots[5]="hypr/theme.conf"
dots[6]="dunst/dunstrc"
dots[7]="BetterDiscord/themes/template.theme.css"
#bat
#spicetify
#vscode
#QT
#GTK

#update configs
for dot in ${dots[@]}; do
    path="$configdir$dot"
    template="$path.j2"
    
    j2 $template $theme -o $path &
    echo "...applied to $path"
done

#update running apps
sleep 0.4
echo "reloading configs..."
eww -c "$configdir/eww/bar" reload 
eww -c "$configdir/eww/dashboard" reload 
pkill -SIGUSR1 kitty 
hyprctl reload 
pkill dunst 

#change wallpaper
echo "changing wallpaper..."
img=$(sed -nr '/^\[img\]/ { :l /^wallpaper[ ]*=/ { s/[^=]*=[ ]*//; p; q;}; n; b l;}' $theme)
echo $HOME$img
swww img $HOME$img

echo "done!"